export const initComponentDomStyleStore: React.CSSProperties = {
  opacity: 1,
  width: 0,
  height: 0,
  position: 'relative',
  textAlign: 'left',
  backgroundColor: '#ffffff',
  color: '#000000',
  fontSize: 14,
  lineHeight: 22,
  letterSpacing: 0,
  borderColor: '#ccc',
  borderWidth: 1,
  borderRadius: 12,
  left: 0,
  right: 0,
  top: 0,
  bottom: 0,
  cursor: 'default'
};
